# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRA_idPR-6OUVvWv7tiAfjo9XntN4pB4
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Olist Dashboard", layout="wide")
st.title("📊 Olist E-Commerce Dashboard")
st.markdown("Analisis Segmentasi Pelanggan (RFM) dan Dampak Keterlambatan Pengiriman")

@st.cache_data
def load_data():
    rfm = pd.read_csv('main_data.csv')
    delay = pd.read_csv('delay_analysis.csv')
    return rfm, delay

rfm, delay = load_data()

# --- Jika kolom 'segment' tidak ada, hitung segmentasi dari data yang ada ---
if 'segment' not in rfm.columns:
    st.info("Kolom 'segment' tidak ditemukan. Menghitung segmentasi dari data transaksi...")

    # Pastikan kolom tanggal sudah datetime
    if 'order_delivered_customer_date' in rfm.columns:
        rfm['order_delivered_customer_date'] = pd.to_datetime(rfm['order_delivered_customer_date'])
        recent_date = rfm['order_delivered_customer_date'].max()

        # Agregasi per customer
        rfm_agg = rfm.groupby('customer_id').agg({
            'order_delivered_customer_date': lambda x: (recent_date - x.max()).days,
            'order_id': 'nunique',
            'payment_value': 'sum'
        }).reset_index()
        rfm_agg.columns = ['customer_id', 'recency', 'frequency', 'monetary']

        # Hapus data tidak valid
        rfm_agg = rfm_agg[(rfm_agg['recency'] >= 0) & (rfm_agg['frequency'] > 0) & (rfm_agg['monetary'] > 0)]

        # Buat skor RFM (1-4) menggunakan qcut
        try:
            rfm_agg['r_rank'] = pd.qcut(rfm_agg['recency'].rank(method='first'), 4, labels=[4,3,2,1]).astype(int)
            rfm_agg['f_rank'] = pd.qcut(rfm_agg['frequency'].rank(method='first'), 4, labels=[1,2,3,4]).astype(int)
            rfm_agg['m_rank'] = pd.qcut(rfm_agg['monetary'].rank(method='first'), 4, labels=[1,2,3,4]).astype(int)
        except:
            # Fallback manual
            rfm_agg['r_rank'] = pd.cut(rfm_agg['recency'], bins=4, labels=[4,3,2,1]).astype(int)
            rfm_agg['f_rank'] = pd.cut(rfm_agg['frequency'], bins=4, labels=[1,2,3,4]).astype(int)
            rfm_agg['m_rank'] = pd.cut(rfm_agg['monetary'], bins=4, labels=[1,2,3,4]).astype(int)

        rfm_agg['rfm_score'] = rfm_agg['r_rank'] + rfm_agg['f_rank'] + rfm_agg['m_rank']

        def get_segment(score):
            if score >= 10: return 'Champions'
            elif score >= 8: return 'Loyal'
            elif score >= 6: return 'Potential'
            else: return 'At Risk'

        rfm_agg['segment'] = rfm_agg['rfm_score'].apply(get_segment)

        # Gunakan data agregat untuk dashboard
        rfm = rfm_agg.rename(columns={'monetary': 'payment_value'})
        st.success("Segmentasi berhasil dibuat!")
    else:
        st.error("Data tidak memiliki kolom 'order_delivered_customer_date' untuk menghitung segmentasi.")
        st.stop()

# Tampilkan dashboard
tab1, tab2 = st.tabs(["🏆 Segmentasi Pelanggan (RFM)", "⏱️ Dampak Keterlambatan"])

with tab1:
    st.subheader("Distribusi Segmen Pelanggan")
    col1, col2 = st.columns(2)
    with col1:
        fig, ax = plt.subplots(figsize=(5,5))
        segment_counts = rfm['segment'].value_counts()
        ax.pie(segment_counts, labels=segment_counts.index, autopct='%1.1f%%', startangle=90, colors=['#2E8B57','#3CB371','#66CDAA','#FFA07A'])
        ax.set_title('Persentase Pelanggan per Segmen')
        st.pyplot(fig)
    with col2:
        fig, ax = plt.subplots(figsize=(6,4))
        segment_revenue = rfm.groupby('segment')['payment_value'].sum().sort_values(ascending=False)
        ax.bar(segment_revenue.index, segment_revenue.values, color=['#2E8B57','#3CB371','#66CDAA','#FFA07A'])
        ax.set_title('Total Pendapatan per Segmen (R$)')
        ax.set_xlabel('Segmen')
        ax.set_ylabel('Pendapatan (R$)')
        plt.xticks(rotation=45)
        st.pyplot(fig)

with tab2:
    st.subheader("Pengaruh Keterlambatan terhadap Skor Ulasan")
    corr = delay['delay_days'].corr(delay['review_score'])
    st.metric("Korelasi Pearson (delay vs review)", f"{corr:.3f}", delta="Negatif" if corr < 0 else "Positif")

    col1, col2 = st.columns(2)
    with col1:
        fig, ax = plt.subplots()
        sns.boxplot(x=delay['delay_days'] > 0, y=delay['review_score'], ax=ax, palette=['#66CDAA', '#FFA07A'])
        ax.set_xticklabels(['Tepat waktu / Lebih awal', 'Terlambat'])
        ax.set_title('Skor Ulasan: Tepat Waktu vs Terlambat')
        st.pyplot(fig)
    with col2:
        avg_on = delay[delay['delay_days'] <= 0]['review_score'].mean()
        avg_late = delay[delay['delay_days'] > 0]['review_score'].mean()
        st.metric("Rata-rata skor tepat waktu", f"{avg_on:.2f}")
        st.metric("Rata-rata skor terlambat", f"{avg_late:.2f}")
        st.metric("Potensi peningkatan", f"{avg_on - avg_late:.2f} poin")

    st.subheader("Top 10 Kategori Paling Sensitif")
    top_cats = delay['product_category_name_english'].value_counts().head(10).index
    cat_delay = delay[delay['product_category_name_english'].isin(top_cats)]
    fig, ax = plt.subplots(figsize=(10,5))
    sns.barplot(data=cat_delay, x='product_category_name_english', y='review_score', hue=cat_delay['delay_days']>0, ax=ax, palette=['#66CDAA','#FFA07A'])
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    ax.set_title('Skor Ulasan: Tepat Waktu vs Terlambat per Kategori')
    ax.legend(title='Status', labels=['Tepat waktu', 'Terlambat'])
    st.pyplot(fig)

st.markdown("---")
st.caption("Dashboard ini dibuat untuk proyek akhir analisis data. Data: Olist E-Commerce Public Dataset.")

